version: '3.1'

services:
  mongodb: 
    image: mongo
    container_name: skill-matcher-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: skill-matcher

  localstack:
    image: localstack/localstack:latest
    container_name: skill-matcher-localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data